export const FETCHING_NEWS = 'FETCHING_NEWS';
export const RECEIVE_NEWS = 'RECEIVE_NEWS';
export const TOGGLE_NEWS = 'TOGGLE_NEWS';

export const FETCHING_STOCK = 'FETCHING_STOCK';
export const RECEIVE_STOCK = 'RECEIVE_STOCK';

export const FETCHING_CRAWLERS = 'FETCHING_CRAWLERS';
export const RECEIVE_CRAWLERS = 'RECEIVE_CRAWLERS';

export const EXEING_CRAWLER = 'FETCHING_CRAWLERS';
export const EXE_CRAWLER_SUCCESS = 'EXE_CRAWLER_SUCCESS';
export const EXE_CRAWLER_FAIL = 'EXE_CRAWLER_FAIL';
