export const FETCHING_NEWS = 'FETCHING_NEWS';
export const RECEIVE_NEWS = 'RECEIVE_NEWS';
export const TOGGLE_NEWS = 'TOGGLE_NEWS';
export const SET_NEWS_PERIOD = 'SET_NEWS_PERIOD';

export const FETCHING_STOCK = 'FETCHING_STOCK';
export const RECEIVE_STOCK = 'RECEIVE_STOCK';

export const FETCHING_CRAWLERS = 'FETCHING_CRAWLERS';
export const RECEIVE_CRAWLERS = 'RECEIVE_CRAWLERS';

export const EXEING_CRAWLER = 'EXEING_CRAWLER';
export const EXE_CRAWLER_SUCCESS = 'EXE_CRAWLER_SUCCESS';
export const EXE_CRAWLER_FAIL = 'EXE_CRAWLER_FAIL';

export const PIN_EVENT_SUCCESS = 'PIN_EVENT_SUCCESS';
export const PIN_EVENT_FAIL = 'PIN_EVENT_FAIL';
export const UNPIN_EVENT_SUCCESS = 'UNPIN_EVENT_SUCCESS';
export const UNPIN_EVENT_FAIL = 'UNPIN_EVENT_FAIL';

export const SELECT_MARK = 'SELECT_MARK';
